server:
  port: 8762
spring:
  application:
    name: eureka-server
  profiles:
    active: peer2
eureka:
  instance:
    hostname: peer2
  client:
    #是否将自己注册到eureka上
#    registerWithEureka: false
    #是否从eureka上获取注册信息
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka